### PR TITLE
Added Notes of COA

### PR DESCRIPTION
**Pull request by SanD204**
Added Notes of COA 2nd Year all ppts of 5 chapter !

### CODE REVIEW

**Comment by footcricket05** [comment]
Hey, Theory directory has the PPTs, are they different??

**Review by footcricket05 — CHANGES_REQUESTED** [review]
Check the Theory directory inside COA, it also has PPTs.
If these PPTs are better than those kindly upload them in that directory

**Comment by SanD204** [comment]
These are the New PPTs According to latest regulation

**Comment by footcricket05** [comment]
Okay great

**Pull request merged**
